# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8bbed9b7-715f-4d2f-b1fb-1f91667bbe5b";
      fsType = "btrfs";
      options = [ "subvol=/__root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1D89-90D8";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = 4;
}
