# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0cc09c3b-27fe-4854-be8e-d2eada087c76";
      fsType = "btrfs";
      options = [ "subvol=__root" ];
    };

  fileSystems."/mnt/btrfs-root" =
    { device = "/dev/disk/by-uuid/0cc09c3b-27fe-4854-be8e-d2eada087c76";
      fsType = "btrfs";
      options = [ "subvol=/" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1D89-90D8";
      fsType = "vfat";
    };

  fileSystems."/tmp" =
    { device = "tmpfs";
      fsType = "tmpfs";
    };

  fileSystems."/mnt/biggie" =
    { device = "/dev/sdb5";
      fsType = "btrfs";
      options = [ "subvol=/" ];
    };

  swapDevices = [ ];
  nix.maxJobs = lib.mkDefault 16;
}
